### ISSUE TITLE
Can't find the driver

### ISSUE THREAD

**Issue by aevitas** [microsoft/playwright-sharp#1226]
Greetings,

I've been using Playwright Sharp and it's been working really well on my local development machine. However, when I try to deploy my application to one of my servers, I am sometimes greeted with the following exception:

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Driver not found in any of the locations.)
 ---> PlaywrightSharp.PlaywrightSharpException: Driver not found in any of the locations.
   at PlaywrightSharp.Transport.Connection.GetExecutablePath() in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs:line 270
   at PlaywrightSharp.Transport.Connection.GetProcess(String driverExecutablePath) in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs:line 233
   at PlaywrightSharp.Transport.Connection..ctor(ILoggerFactory loggerFactory, TransportTaskScheduler scheduler, String driverExecutablePath, String browsersPath) in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs:line 74
   at PlaywrightSharp.Playwright.CreateAsync(ILoggerFactory loggerFactory, TransportTaskScheduler scheduler, String driverExecutablePath, String browsersPath, String debug) in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/Playwright.cs:line 109
```

This exception is thrown when I call `CreateAsync()` or `InstallAsync()` as well. Here's what I've tried so far:

* Call Create and Install as the first line of code in my application, this only threw the above exception
* Attempt to build and `dotnet publish` my application so the build-time Playwright tools could do their magic
* Ran `npx playwright install` to install any missing drivers. This returns without any errors, but the exception still occurs

The `%USERPROFILE%\AppData\Local\ms-playwright` contains the following directories:

```

    Directory: C:\Users\aevitas\AppData\Local\ms-playwright


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----          3/2/2021   9:49 AM                .links
d-----         2/27/2021  11:33 PM                chromium-844399
d-----         2/28/2021   9:35 AM                chromium-854489
d-----         2/28/2021   9:35 AM                ffmpeg-1005
d-----         2/27/2021  11:33 PM                firefox-1225
d-----         2/28/2021   9:35 AM                firefox-1234
d-----         2/27/2021  11:33 PM                webkit-1423
d-----         2/28/2021   9:35 AM                webkit-1438
```

Playwright did initially work on this server for a while, but after a redeploy without any significant code changes, it randomly stopped working. Is there anything I'm missing here?

Thanks!

**Comment by kblok** [comment]
Did you try v0.191.1?

**Comment by aevitas** [comment]
Yes, both times I was using 0.191.1. I see there's a .2 version available now, should I try that one too?

**Comment by kblok** [comment]
I will give a look at the dotnet publish task.

**Comment by aevitas** [comment]
Thank you! If there's anything I can do to help, or any additional information you require please let me know, I'd be more than happy to help out.

**Comment by kblok** [comment]
@aevitas just to have more context. What's the type of app you are publishing, what's the .NET version and the destination OS? :)

**Comment by aevitas** [comment]
I'm publishing an ASP.NET Core app on .NET 5 to win-x64. I'm debugging on a Windows 10 machine as well, under .NET 5. 

Is proper installation and configuration of the browsers only possible through publishing? Because I publish on my development machine, and run the resulting published package on my server by simply running the .exe directly. No publishing or building occurs on that machine.

**Comment by aevitas** [comment]
Found the problem. When installing PlaywrightShap in one of my assemblies, and referencing that assembly from my application assembly, I can use the `Playwright` class "indirectly", without having a reference to PlaywrightSharp in my executable project.

This means that the build steps required to properly install and configure Playwright never actually run, most of the time. Adding a reference to PlaywrightSharp to my executable projects solved the problem.

A few interesting points:

* Docker builds did not seem to follow this pattern, a `docker build` would still run the PW install stuff
* At some point, it did work with an indirect reference

Either way, I don't know how I'd fix this in code as I'm not proficient in MSBuild enough to propose such a change, so I'll be closing this ticket.

Thanks for the help and for the great work on PlaywrightSharp.

**Comment by sleeuwen** [comment]
I have this same issue in multiple projects of mine (.NET 5 on linux, running in xUnit projects as well as normal console projects), however I'd rather not reference `PlaywrightSharp` in my main project and would like to have it transparently copy the drivers over. This is how it used to work in version 0.180.0 (and for that reason I'm still using it).

@kblok is there something I can help with to get this fixed? from my observations it happened between versions 0.180.0 and 0.191.0 and occurs when you don't directly depend on `PlaywrightSharp`. (also, can this issue be reopened as this issue is not fixed)

**Comment by kblok** [comment]
@sleeuwen this is what was going on in the past few versions.
Until v0.180.0 the playwright driver was just a few executables. So we were able to deploy that using the `runtimes` folder in nuget.
A few versions ago we started getting the driver with no executable. Basically the node source code.
We found that nugget didn't support sub-directories in the runtime folder (https://github.com/microsoft/playwright-sharp/issues/1145) that's why we move to build tasks. But the build task needs to know the output directory. That's why we need a reference in the output project.

I don't like this. I think this could be better. But as Playwright is designed for UI Testing we consider this important, but not a blocker.

I would gladly review any PR trying to improve this.

**Comment by sleeuwen** [comment]
@kblok Thank you for explaining why this was changed, I wasn't aware of the behind the scenes changes made in 0.190.0 with regards to the drivers.
I have created a library that integrates xUnit with PlaywrightSharp to more easily write UI tests and that is what we use in our company for multiple projects (it is currently only available internally but I am considering open sourcing it). It's a shame that we will have to add direct references to PlaywrightSharp when upgrading, but at least now I understand why it is needed.

**Comment by ChadNedzlek** [comment]
I've tried versions 170, 180, and 191, publishing for win7-64, win7-86, self contained and framework dependent... But whenever I "dotnet publish", the resulting executable cannot find the drivers when I call CreateAsync ... is there something special I have to do?  Some of those combinations have a "native" folder with a "browsers.json" file, some don't, but none function.

**Comment by ChadNedzlek** [comment]
Ah, so it's not expected to work right now.  Thanks for the info. I eagerly await a fix, and I'll try it out as soon as it's available and can hopefully provide feedback if that would help. Is there another issue that isn't closed tracking this work, so that I can follow it?

**Comment by kblok** [comment]
I thought we had one @ChadNedzlek. I'm reopening this one.

**Comment by pkrakowiak** [comment]
We seem to be having the same issue. It's a .NET Core 3.1 Web Api project that depends on Playwright 0.190.2 from NuGet. I have a `await Playwright.CreateAsync()` call in a static class, as far as I understand it should try to install the driver(s) indirectly. It all works fine on my dev machine because `playwright.cmd install` is ran as part of the build process by MSBuild but it throws the exception seen in the OP's post when ran on the server (built by TeamCity and deployed by Octopus).

In the docs there is [an example of how to install on the server](https://playwrightsharp.dev/documentation/index.html#playwright-dependencies) but we were unable to locate the executable. Is that documentation still valid?

**Comment by nautilux2** [comment]
@pkrakowiak 
Did you had  `await Playwright.InstallAsync();` before ?

**Comment by m-horne** [comment]
For Web API 3.1 app we tried to use InstallAsync but it did not appear to do anything.  I suspect because of a rights issue on the server.  

To get everything working, in TeamCity we needed to package the bin folder rather than package the publish folder (publish of the .NET Core 3.1 project did not include the .playright folder, but the bin folder does).  

After that and a successful deployment to the target server, playwright-sharp appears to try and install the browser cache into the system profiles folder but the process does not have rights.  You need to give the app domain permission to the system profile folder and then it will start working.  

A better solution would be to pre-install the browser cache in a specific location during deployment using the dotnet tools but we were unable to get the tooling to work.  Would be great if there was some documentation for the tooling and a few examples.

**Comment by ChadNedzlek** [comment]
I also tried calling "InstallAsync", but not in a web server context... when running the program as administrator after dotnet publish, and it also seems to have done nothing in that context.

**Comment by jitterbox** [comment]
Just hit the same problem trying to run .NET 5 test project in Azure DevOps. Any workarounds besides packaging /bin?

**Comment by nautilux2** [comment]
@jitterbox 
My workaround is copy the .playwright folder to image then chmod folder to run script
`FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
ARG source
WORKDIR /app
RUN apt-get clean && apt-get update && apt-get install -y apt-transport-https 
RUN apt-get install -y gstreamer1.0-libav libnss3 libatk1.0 libatk-bridge2.0-0 libgbm-dev libgtk-3-0
COPY ${source:-obj/Docker/publish} .
RUN chmod -R 775 /app/.playwright
ENTRYPOINT ["dotnet", "entry.dll"]`

**Comment by fr4gles** [comment]
We have same problem after calling dotnet publish (donet5.0 / windows 10 / windows server 2019).
Our scenario: we are publishing tests and then consume them by running test groups separately by multiple azure pipeline agents.

**Comment by Mfolmer** [comment]
We are experience the same issue after publish from Azure devops to web app. Everything works locally even with publish build. 

ASP.NET Core, net5.0.

Any progress on this?

**Comment by jitterbox** [comment]
The workaround I came up with for a DevOps build pipeline is to add a Copy Files task after the build and before publishing artifacts for deployment.

![image](https://user-images.githubusercontent.com/6708273/114902166-905bbb80-9de3-11eb-8fca-3dff7e369f94.png)
![image](https://user-images.githubusercontent.com/6708273/114902482-dfa1ec00-9de3-11eb-99c6-0b33984e1e5e.png)

**Comment by jitterbox** [comment]
@ChadNedzlek is working on this.

**Comment by fr4gles** [comment]
In my case playwright is not copied automatically even locally.
Used dotnet publish command to minimize published folder size: `dotnet publish "<csproj name>.csproj" --output="bin\_publish" --verbosity="normal" --framework="net5.0" --configuration="Release" --runtime="win-x64" --self-contained="false"`

But based on @Mfolmer reply I've figured it out and prepared workaround (please note `win-x64`).
```
  <!-- remove this target if this is fixed: https://github.com/microsoft/playwright-sharp/issues/1226 -->
  <Target Name="PostPublish" AfterTargets="Publish">
    <ItemGroup>
      <PlaywrightContent Include="$(TargetDir).playwright\win-x64\**\*.*"/>
    </ItemGroup>
    <Copy SourceFiles="@(PlaywrightContent)" DestinationFiles="@(PlaywrightContent->'$(PublishDir)\.playwright\win-x64\%(RecursiveDir)%(Filename)%(Extension)')"/>
  </Target>
```

**Comment by Mfolmer** [comment]
Even with the `.playwright` folder directly in the publish directory with the Azure pipeline copy step, I get a 
`Failed to launch chromium because executable doesn't exist at C:\local\LocalAppData\ms-playwright\chromium-854489\chrome-win\chrome.exe Try re-installing the browsers running `playwright.cmd install` in windows o`
When the web app is deployed and the `await Playwright.CreateAsync()` is invoked.

Any tips?

**Comment by nautilux2** [comment]
> 
> 
> Even with the `.playwright` folder directly in the publish directory with the Azure pipeline copy step, I get a
> `Failed to launch chromium because executable doesn't exist at C:\local\LocalAppData\ms-playwright\chromium-854489\chrome-win\chrome.exe Try re-installing the browsers running 'playwright.cmd install' in windows ...`
> When the web app is deployed and the `await Playwright.CreateAsync()` is invoked.
> 
> Any tips?

pls verify content of .playwright folder, if your folder does not contain the node_modules folder then install dependency by `npm install`  and then in code call `await Playwright.InstallAsync()` before `await Playwright.CreateAsync()`

**Comment by Mfolmer** [comment]
Now it seems to find everything just find. However, now I get the following message then trying to invoke `await Playwright.InstallAsync()` or `await Playwright.CreateAsync()`:

> The specified executable is not a valid application for this OS platform.

According to the documentation: 

> Then, the platform-specific driver will be picked at run-time.

I'm really puzzled why this happens. Any clues?

**Comment by nautilux2** [comment]
> Now it seems to find everything just find. However, now I get the following message then trying to invoke `await Playwright.InstallAsync()` or `await Playwright.CreateAsync()`:
> 
> > The specified executable is not a valid application for this OS platform.
> 
> According to the documentation: 
> 
> > Then, the platform-specific driver will be picked at run-time.
> 
> I'm really puzzled why this happens. Any clues? 
> 
> 
> 

When you call installAsync or createAsync, playwright will look into .playwright folder and with each OS, there will be a folder with application ( macos, linux, winx64, winx86). Pls check if you have right application folder for your Os.

**Comment by Mfolmer** [comment]
It seems to all be in there 
- osx
- unix
- win-x64
- win-x86

**Comment by nautilux2** [comment]
> It seems to all be in there 
> - osx
> - unix
> - win-x64
> - win-x86
> 

Yep, but pls check if it has node_modules folder because it's ignored default in .gitignore file.

**Comment by Mfolmer** [comment]
The directory for win-x86 looks like this, the other looks similar.

![image](https://user-images.githubusercontent.com/17977644/115589132-c8756980-a2cf-11eb-956f-212c77a30c0e.png)

**Comment by nautilux2** [comment]
> The directory for win-x86 looks like this, the other looks similar.
> 
> ![image](https://user-images.githubusercontent.com/17977644/115589132-c8756980-a2cf-11eb-956f-212c77a30c0e.png)
> 

Pls check if user has enough permission to execute script and/or verify .playwright location

**Comment by Mfolmer** [comment]
> > The directory for win-x86 looks like this, the other looks similar.
> > ![image](https://user-images.githubusercontent.com/17977644/115589132-c8756980-a2cf-11eb-956f-212c77a30c0e.png)
> 
> Pls check if user has enough permission to execute script and/or verify .playwright location

Hi, sorry for the late reply. 

Do it need write permissions?
Just notice that when deploying a web app to Azure as a zip package it will be mounted directly as the read-only directory. Had issues with other services requiring write permission.

**Comment by ChadNedzlek** [comment]
I'm confused by a lot of the comments here.  My understanding/desire is that this should "just work".  Like if I build an app that uses playwright, the app should work the same as if I hit F5 inside VS.  A lot of the comments here seem to include a lot of zip file copying around and explicit permission settings.

Is the goal that it should "just work" and the comments are desperately (and apparently unsuccessfully) trying to come up with a workaround until that happens?

**Comment by aevitas** [comment]
It does work out of the box as long as the executing assembly has a direct
reference to the playwright package. This sometimes isn't desirable, so
what you're reading in the comments are attempts at working around this
limitation.

Bottom line is you need the proper build steps. The package sorts it for
you automatically, but if you don't want a direct reference, you have to
scramble.

**Comment by ChadNedzlek** [comment]
I made a direct reference to the package and mine definitely does not work.  If that's not expected, it seems like there is a bug somewhere.  What version is expected to work with?  (And are there any particular configurations/platforms/publish styles I should use)

**Comment by ChadNedzlek** [comment]
This is my entire proj file:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RootNamespace>bot_web</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.3.0" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.1.0" />
    <PackageReference Include="Mono.Options" Version="6.6.0.161" />
    <PackageReference Include="PlaywrightSharp" Version="0.192.0" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="5.0.0" />
  </ItemGroup>

</Project>
```

If I run "dotnet publish", the resulting exe cannot find the driver.

**Comment by kblok** [comment]
@ChadNedzlek, `dotnet publish` is not supported yet. It will be, but the primary use case right now is using Playwright as a UI testing tool. 
If you need to publish you project you should copy the drivers file manually. 

Why isn't it working?
We have some copy tasks during the build that are not being executed on publish. We need to figure out how to fix that. PRs are welcome :)

**Comment by andreasvatne** [comment]
@kblok Do you know when a new release including the `dotnet publish` fix will be released?

**Comment by avodovnik** [comment]
@andreasvatne We've published a significant new release this morning - now available as `Microsoft.Playwright` on NuGet. It should also fix the problem you were seeing.

**Comment by ChadNedzlek** [comment]
I tried Microsoft.Playwright 1.12.1, and it still fails to find the driver when I do "dotnet publish".  And now it doesn't even work when I debug in VS.

**Comment by ChadNedzlek** [comment]
The published version fails in "CreateAsync".  The debugging fails at "LauchAsync".

**Comment by andreasvatne** [comment]
@ChadNedzlek It seems like you now need to run the `playwright install` CLI command both on Windows and Linux (Debian only) for it to work. I only tried for about 10 minutes, so I don't have a solution yet but that's what I got from a quick look at the docs.

**Comment by ChadNedzlek** [comment]
Where do I find that command?  All I have right now is the assembly reference.  But the new behavior seems strictly less useful than the old behavior, so I'm probably just going to revert to the old, deprecated assembly.

Making everyone that tries to use my repository have to run some command line stuff to run the tests in VS isn't a behavior I want.

**Comment by andreasvatne** [comment]
There's a link under the [release notes](https://github.com/microsoft/playwright-dotnet/releases/tag/v1.12.1) (Breaking changes). It points you to the [Getting started](https://playwright.dev/dotnet/docs/intro/#first-project) page where you'll find some more information.

**Comment by ChadNedzlek** [comment]
Is there any chance this will get fixed in the future? Otherwise I'm going to look at other automation frameworks.

**Comment by andreasvatne** [comment]
I literally just got the old version (0.192) working yesterday, so I will keep that for now. It works both while debugging and also in a Docker container. The only drawback is that I need to reference PlaywrightSharp in the host project and add this in the .csproj file (as described earlier in this thread):

> ```
>   
>   <Target Name="PostPublish" AfterTargets="Publish">
>     <ItemGroup>
>       <PlaywrightContent Include="$(TargetDir).playwright\win-x64\**\*.*"/>
>     </ItemGroup>
>     <Copy SourceFiles="@(PlaywrightContent)" DestinationFiles="@(PlaywrightContent->'$(PublishDir)\.playwright\win-x64\%(RecursiveDir)%(Filename)%(Extension)')"/>
>   </Target>
> ```

**Comment by thomaschanneladvisor** [comment]
@ChadNedzlek 
`dotnet tool install --global Microsoft.Playwright.CLI`
then
`playwright install`
then run your code calling Playwright.CreateAsync and Playwright.LaunchAsync , that worked for me locally - have yet to try on a server in CI but will be soon

**Comment by markm77** [comment]
I was using Visual Studio's remote testing feature to run my tests and debug in WSL2 (Linux) and having a lot of trouble with I believe this issue.

Mainly because remote testing in WSL does not re-build a project in Linux but I believe simply mounts the Windows files and runs the assemblies built by Windows. The consequence is `playwright install` only works on the Windows side (and not on the Linux side - it complains about not having required assets).

Unfortunately although re-building the project using the mounted files in Linux might work this is very slow and seems to break the whole project on the Windows side and is not a workable solution.

My eventual solution was to run the following on the Linux side from the project root
```
cd bin/Debug/net6.0/.playwright/node
cp -r  ~/.nuget/packages/microsoft.playwright/1.21.0/.playwright/node/linux/ .
```

Now Playwright tests work on both Windows and WSL2. Any comments or corrections to this fix welcome.

(Also nice to see the Linux Playwright browser window appear in Windows (new WSL2 UI feature).)

**Comment by markm77** [comment]
PS: Is it possible to adjust the Playwright build so that it copies drivers for multiple OSes? I don't mind running `playwright install` in a target OS before running/debugging but also having to do a copy step like the above is very messy.

**Comment by markm77** [comment]
Okay, many thanks, wish I'd noticed that earlier. 🙂
